package com.reviveai.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(
        name = "payment_attempts",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_payment_idempotency_key",
                        columnNames = "idempotency_key"
                ),
                @UniqueConstraint(
                        name = "uk_payment_external_id",
                        columnNames = "external_payment_id"
                )
        },
        indexes = {
                @Index(
                        name = "idx_payment_subscription_id",
                        columnList = "subscription_id"
                ),
                @Index(
                        name = "idx_payment_status",
                        columnList = "status"
                ),
                @Index(
                        name = "idx_payment_attempted_at",
                        columnList = "attempted_at"
                ),
                @Index(
                        name = "idx_payment_external_order_id",
                        columnList = "external_order_id"
                ),
                @Index(
                        name = "idx_payment_recovery_case_id",
                        columnList = "recovery_case_id"
                )
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PaymentAttempt {

    // =========================================================
    // ID
    // =========================================================

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;


    // =========================================================
    // SUBSCRIPTION
    // =========================================================

    /**
     * Subscription for which this payment was attempted.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
            name = "subscription_id",
            nullable = false,
            foreignKey = @ForeignKey(
                    name = "fk_payment_subscription"
            )
    )
    private Subscription subscription;


    // =========================================================
    // RECOVERY CASE
    // =========================================================

    /**
     * Recovery case associated with this payment attempt.
     *
     * This is populated when the payment attempt belongs
     * to the recovery pipeline.
     *
     * Normal payment attempts may have this value as null.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
            name = "recovery_case_id",
            foreignKey = @ForeignKey(
                    name = "fk_payment_recovery_case"
            )
    )
    private RecoveryCase recoveryCase;


    // =========================================================
    // EXTERNAL ORDER ID
    // =========================================================

    /**
     * Razorpay Order ID associated with this payment attempt.
     *
     * Multiple payment attempts can belong to the same
     * Razorpay order.
     */
    @Column(
            name = "external_order_id",
            length = 150
    )
    private String externalOrderId;


    // =========================================================
    // EXTERNAL PAYMENT ID
    // =========================================================

    /**
     * Payment ID generated by the external payment gateway.
     *
     * This identifies a particular payment attempt.
     */
    @Column(
            name = "external_payment_id",
            length = 150
    )
    private String externalPaymentId;


    // =========================================================
    // IDEMPOTENCY KEY
    // =========================================================

    /**
     * Prevents duplicate processing of the same payment request.
     */
    @Column(
            name = "idempotency_key",
            nullable = false,
            length = 150
    )
    private String idempotencyKey;


    // =========================================================
    // AMOUNT
    // =========================================================

    /**
     * Payment amount.
     */
    @Column(
            nullable = false,
            precision = 12,
            scale = 2
    )
    private BigDecimal amount;


    // =========================================================
    // STATUS
    // =========================================================

    /**
     * Current status of this payment attempt.
     */
    @Enumerated(EnumType.STRING)
    @Column(
            nullable = false,
            length = 20
    )
    @Builder.Default
    private PaymentStatus status = PaymentStatus.PENDING;


    // =========================================================
    // GATEWAY ERROR CODE
    // =========================================================

    /**
     * Error code returned by payment gateway.
     */
    @Column(
            name = "gateway_error_code",
            length = 100
    )
    private String gatewayErrorCode;


    // =========================================================
    // GATEWAY ERROR MESSAGE
    // =========================================================

    /**
     * Human-readable error returned by payment gateway.
     */
    @Column(
            name = "gateway_error_message",
            columnDefinition = "TEXT"
    )
    private String gatewayErrorMessage;


    // =========================================================
    // ATTEMPTED AT
    // =========================================================

    /**
     * Time at which this payment attempt was created.
     */
    @Column(
            name = "attempted_at",
            nullable = false
    )
    private OffsetDateTime attemptedAt;


    // =========================================================
    // PRE-PERSIST
    // =========================================================

    /**
     * Initialize default values before persisting.
     */
    @PrePersist
    protected void onCreate() {

        if (this.attemptedAt == null) {
            this.attemptedAt = OffsetDateTime.now();
        }

        if (this.status == null) {
            this.status = PaymentStatus.PENDING;
        }
    }


    // =========================================================
    // PAYMENT STATUS
    // =========================================================

    /**
     * Payment attempt lifecycle status.
     */
    public enum PaymentStatus {

        /**
         * Payment attempt has been created but
         * the final gateway result is not known.
         */
        PENDING,

        /**
         * Payment was successfully completed.
         */
        SUCCESS,

        /**
         * Payment attempt failed.
         */
        FAILED
    }
}
