package com.reviveai.entity;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(
        name = "payment_attempts",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_payment_idempotency_key",
                        columnNames = "idempotency_key"
                ),
                @UniqueConstraint(
                        name = "uk_payment_external_id",
                        columnNames = "external_payment_id"
                )
        },
        indexes = {
                @Index(
                        name = "idx_payment_subscription_id",
                        columnList = "subscription_id"
                ),
                @Index(
                        name = "idx_payment_status",
                        columnList = "status"
                ),
                @Index(
                        name = "idx_payment_attempted_at",
                        columnList = "attempted_at"
                )
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PaymentAttempt {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * Subscription for which this payment was attempted.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
            name = "subscription_id",
            nullable = false,
            foreignKey = @ForeignKey(name = "fk_payment_subscription")
    )
    private Subscription subscription;

    /**
     * Payment ID generated by the external payment gateway.
     */
    @Column(
            name = "external_payment_id",
            length = 150
    )
    private String externalPaymentId;

    /**
     * Prevents duplicate processing of the same payment request.
     */
    @Column(
            name = "idempotency_key",
            nullable = false,
            length = 150
    )
    private String idempotencyKey;

    /**
     * Payment amount.
     */
    @Column(
            nullable = false,
            precision = 12,
            scale = 2
    )
    private BigDecimal amount;

    @Enumerated(EnumType.STRING)
    @Column(
            nullable = false,
            length = 20
    )
    @Builder.Default
    private PaymentStatus status = PaymentStatus.PENDING;

    /**
     * Error code returned by payment gateway.
     */
    @Column(
            name = "gateway_error_code",
            length = 100
    )
    private String gatewayErrorCode;

    /**
     * Human-readable error returned by payment gateway.
     */
    @Column(
            name = "gateway_error_message",
            columnDefinition = "TEXT"
    )
    private String gatewayErrorMessage;

    @Column(
            name = "attempted_at",
            nullable = false
    )
    private OffsetDateTime attemptedAt;

    @PrePersist
    protected void onCreate() {

        if (this.attemptedAt == null) {
            this.attemptedAt = OffsetDateTime.now();
        }

        if (this.status == null) {
            this.status = PaymentStatus.PENDING;
        }
    }

    public enum PaymentStatus {
        PENDING,
        SUCCESS,
        FAILED
    }
}